---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: centos-7.2
  driver_config:
    network:
    - ["forwarded_port", {guest: 8090, host: 8090}]
    - ["private_network", {ip: "192.168.33.35"}]

suites:
  - name: default
    run_list:
      - recipe[in_demo::default]
    attributes:
