---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: centos-7.2
  driver:
    network:
      - ["private_network", {ip: "192.168.22.100"}]

suites:
  - name: default
    run_list:
      - recipe[in_demo::default]
    attributes:
