---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[in_demo::default]
    attributes:
